# Challenge 1

In this challenge you will be working on **Pokemon**. You will answer a series of questions in order to practice dataframe calculation, aggregation, and transformation.

![Pokemon](../images/pokemon.jpg)

Follow the instructions below and enter your code.

#### Import all required libraries.

In [291]:
# import libraries
import numpy as np
import pandas as pd

#### Import data set.

Import data set `Pokemon` from Ironhack's database. Read the data into a dataframe called `pokemon`.

*Data set attributed to [Alberto Barradas](https://www.kaggle.com/abcsds/pokemon/)*

In [292]:
# import data set from Ironhack's database
pokemon=pd.read_csv('C:/Users/Camille/Documents/Ecole/Ironhack/0323_2020DATAPAR/Labs/module_1/Dataframe-Calculations/Pokemon.csv')

#### Print first 10 rows of `pokemon`.

In [293]:
# your code here
pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

When you look at a data set, you often wonder what each column means. Some open-source data sets provide descriptions of the data set. In many cases, data descriptions are extremely useful for data analysts to perform work efficiently and successfully.

For the `Pokemon.csv` data set, fortunately, the owner provided descriptions which you can see [here](https://www.kaggle.com/abcsds/pokemon/home). For your convenience, we are including the descriptions below. Read the descriptions and understand what each column means. This knowledge is helpful in your work with the data.

| Column | Description |
| --- | --- |
| # | ID for each pokemon |
| Name | Name of each pokemon |
| Type 1 | Each pokemon has a type, this determines weakness/resistance to attacks |
| Type 2 | Some pokemon are dual type and have 2 |
| Total | A general guide to how strong a pokemon is |
| HP | Hit points, or health, defines how much damage a pokemon can withstand before fainting |
| Attack | The base modifier for normal attacks (eg. Scratch, Punch) |
| Defense | The base damage resistance against normal attacks |
| SP Atk | Special attack, the base modifier for special attacks (e.g. fire blast, bubble beam) |
| SP Def | The base damage resistance against special attacks |
| Speed | Determines which pokemon attacks first each round |
| Generation | Number of generation |
| Legendary | True if Legendary Pokemon False if not |

#### Obtain the distinct values across `Type 1` and `Type 2`.

Exctract all the values in `Type 1` and `Type 2`. Then create an array containing the distinct values across both fields.

In [294]:
# your code here
[pokemon['Type 1'], pokemon['Type 2']]

[0        Grass
 1        Grass
 2        Grass
 3        Grass
 4         Fire
         ...
 795       Rock
 796       Rock
 797    Psychic
 798    Psychic
 799       Fire
 Name: Type 1, Length: 800, dtype: object,
 0      Poison
 1      Poison
 2      Poison
 3      Poison
 4         NaN
         ...
 795     Fairy
 796     Fairy
 797     Ghost
 798      Dark
 799     Water
 Name: Type 2, Length: 800, dtype: object]

In [295]:
pokemon['Type 1'].unique()

array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
       'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
       'Dragon', 'Dark', 'Steel', 'Flying'], dtype=object)

In [296]:
pokemon['Type 2'].unique()

array(['Poison', nan, 'Flying', 'Dragon', 'Ground', 'Fairy', 'Grass',
       'Fighting', 'Psychic', 'Steel', 'Ice', 'Rock', 'Dark', 'Water',
       'Electric', 'Fire', 'Ghost', 'Bug', 'Normal'], dtype=object)

In [297]:
[pokemon['Type 1'].unique(), pokemon['Type 2'].unique()]

[array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
        'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
        'Dragon', 'Dark', 'Steel', 'Flying'], dtype=object),
 array(['Poison', nan, 'Flying', 'Dragon', 'Ground', 'Fairy', 'Grass',
        'Fighting', 'Psychic', 'Steel', 'Ice', 'Rock', 'Dark', 'Water',
        'Electric', 'Fire', 'Ghost', 'Bug', 'Normal'], dtype=object)]

In [327]:
pokemon[['Type 1', 'Type 2']].apply(lambda x: tuple(set((x['Type 1'], x['Type 2']))), axis=1)

array([('Grass', 'Poison'), ('Grass', 'Poison'), ('Grass', 'Poison'),
       ('Grass', 'Poison'), (nan, 'Fire'), (nan, 'Fire'),
       ('Flying', 'Fire'), ('Fire', 'Dragon'), ('Flying', 'Fire'),
       (nan, 'Water'), (nan, 'Water'), (nan, 'Water'), (nan, 'Water'),
       (nan, 'Bug'), (nan, 'Bug'), ('Bug', 'Flying'), ('Bug', 'Poison'),
       ('Bug', 'Poison'), ('Bug', 'Poison'), ('Bug', 'Poison'),
       ('Normal', 'Flying'), ('Normal', 'Flying'), ('Normal', 'Flying'),
       ('Normal', 'Flying'), ('Normal', nan), ('Normal', nan),
       ('Normal', 'Flying'), ('Normal', 'Flying'), (nan, 'Poison'),
       (nan, 'Poison'), ('Electric', nan), ('Electric', nan),
       (nan, 'Ground'), (nan, 'Ground'), (nan, 'Poison'), (nan, 'Poison'),
       ('Poison', 'Ground'), (nan, 'Poison'), (nan, 'Poison'),
       ('Poison', 'Ground'), (nan, 'Fairy'), (nan, 'Fairy'),
       (nan, 'Fire'), (nan, 'Fire'), ('Normal', 'Fairy'),
       ('Normal', 'Fairy'), ('Flying', 'Poison'), ('Flying', 'Poison'),
       ('Grass', 'Poison'), ('Grass', 'Poison'), ('Grass', 'Poison'),
       ('Grass', 'Bug'), ('Grass', 'Bug'), ('Bug', 'Poison'),
       ('Bug', 'Poison'), (nan, 'Ground'), (nan, 'Ground'),
       ('Normal', nan), ('Normal', nan), (nan, 'Water'), (nan, 'Water'),
       (nan, 'Fighting'), (nan, 'Fighting'), (nan, 'Fire'), (nan, 'Fire'),
       (nan, 'Water'), (nan, 'Water'), ('Water', 'Fighting'),
       (nan, 'Psychic'), (nan, 'Psychic'), (nan, 'Psychic'),
       (nan, 'Psychic'), (nan, 'Fighting'), (nan, 'Fighting'),
       (nan, 'Fighting'), ('Grass', 'Poison'), ('Grass', 'Poison'),
       ('Grass', 'Poison'), ('Water', 'Poison'), ('Water', 'Poison'),
       ('Rock', 'Ground'), ('Rock', 'Ground'), ('Rock', 'Ground'),
       (nan, 'Fire'), (nan, 'Fire'), ('Psychic', 'Water'),
       ('Psychic', 'Water'), ('Psychic', 'Water'), ('Electric', 'Steel'),
       ('Electric', 'Steel'), ('Normal', 'Flying'), ('Normal', 'Flying'),
       ('Normal', 'Flying'), (nan, 'Water'), ('Ice', 'Water'),
       (nan, 'Poison'), (nan, 'Poison'), (nan, 'Water'), ('Ice', 'Water'),
       ('Ghost', 'Poison'), ('Ghost', 'Poison'), ('Ghost', 'Poison'),
       ('Ghost', 'Poison'), ('Rock', 'Ground'), (nan, 'Psychic'),
       (nan, 'Psychic'), (nan, 'Water'), (nan, 'Water'),
       ('Electric', nan), ('Electric', nan), ('Grass', 'Psychic'),
       ('Grass', 'Psychic'), (nan, 'Ground'), (nan, 'Ground'),
       (nan, 'Fighting'), (nan, 'Fighting'), ('Normal', nan),
       (nan, 'Poison'), (nan, 'Poison'), ('Rock', 'Ground'),
       ('Rock', 'Ground'), ('Normal', nan), (nan, 'Grass'),
       ('Normal', nan), ('Normal', nan), (nan, 'Water'), (nan, 'Water'),
       (nan, 'Water'), (nan, 'Water'), (nan, 'Water'),
       ('Psychic', 'Water'), ('Psychic', 'Fairy'), ('Bug', 'Flying'),
       ('Ice', 'Psychic'), ('Electric', nan), (nan, 'Fire'), (nan, 'Bug'),
       ('Bug', 'Flying'), ('Normal', nan), (nan, 'Water'),
       ('Water', 'Flying'), ('Water', 'Dark'), ('Ice', 'Water'),
       ('Normal', nan), ('Normal', nan), (nan, 'Water'),
       ('Electric', nan), (nan, 'Fire'), ('Normal', nan),
       ('Rock', 'Water'), ('Rock', 'Water'), ('Rock', 'Water'),
       ('Rock', 'Water'), ('Rock', 'Flying'), ('Rock', 'Flying'),
       ('Normal', nan), ('Ice', 'Flying'), ('Electric', 'Flying'),
       ('Flying', 'Fire'), (nan, 'Dragon'), (nan, 'Dragon'),
       ('Flying', 'Dragon'), (nan, 'Psychic'), ('Psychic', 'Fighting'),
       (nan, 'Psychic'), (nan, 'Psychic'), (nan, 'Grass'), (nan, 'Grass'),
       (nan, 'Grass'), (nan, 'Fire'), (nan, 'Fire'), (nan, 'Fire'),
       (nan, 'Water'), (nan, 'Water'), (nan, 'Water'), ('Normal', nan),
       ('Normal', nan), ('Normal', 'Flying'), ('Normal', 'Flying'),
       ('Bug', 'Flying'), ('Bug', 'Flying'), ('Bug', 'Poison'),
       ('Bug', 'Poison'), ('Flying', 'Poison'), ('Electric', 'Water'),
       ('Electric', 'Water'), ('Electric', nan), (nan, 'Fairy'),
       ('Normal', 'Fairy'), (nan, 'Fairy'), ('Flying', 'Fairy'),
       ('Psychic', 'Flying'), ('Psychic', 'Flying'), ('Electric', nan),
       ('Electric', nan), ('Electric', nan), ('Electric', 'Dragon'),
       (nan, 'Grass'), ('Water', 'Fairy'), ('Water', 'Fairy'),
       ('Rock', nan), (nan, 'Water'), ('Grass', 'Flying'),
       ('Grass', 'Flying'), ('Grass', 'Flying'), ('Normal', nan),
       (nan, 'Grass'), (nan, 'Grass'), ('Bug', 'Flying'),
       ('Water', 'Ground'), ('Water', 'Ground'), (nan, 'Psychic'),
       (nan, 'Dark'), ('Flying', 'Dark'), ('Psychic', 'Water'),
       (nan, 'Ghost'), (nan, 'Psychic'), (nan, 'Psychic'),
       ('Normal', 'Psychic'), (nan, 'Bug'), ('Bug', 'Steel'),
       ('Normal', nan), ('Flying', 'Ground'), ('Steel', 'Ground'),
       ('Steel', 'Ground'), (nan, 'Fairy'), (nan, 'Fairy'),
       ('Water', 'Poison'), ('Bug', 'Steel'), ('Bug', 'Steel'),
       ('Rock', 'Bug'), ('Bug', 'Fighting'), ('Bug', 'Fighting'),
       ('Ice', 'Dark'), ('Normal', nan), ('Normal', nan), (nan, 'Fire'),
       ('Rock', 'Fire'), ('Ice', 'Ground'), ('Ice', 'Ground'),
       ('Rock', 'Water'), (nan, 'Water'), (nan, 'Water'),
       ('Ice', 'Flying'), ('Water', 'Flying'), ('Flying', 'Steel'),
       ('Fire', 'Dark'), ('Fire', 'Dark'), ('Fire', 'Dark'),
       ('Water', 'Dragon'), (nan, 'Ground'), (nan, 'Ground'),
       ('Normal', nan), ('Normal', nan), ('Normal', nan),
       (nan, 'Fighting'), (nan, 'Fighting'), ('Ice', 'Psychic'),
       ('Electric', nan), (nan, 'Fire'), ('Normal', nan), ('Normal', nan),
       ('Electric', nan), (nan, 'Fire'), (nan, 'Water'),
       ('Rock', 'Ground'), ('Rock', 'Ground'), ('Rock', 'Dark'),
       ('Rock', 'Dark'), ('Psychic', 'Flying'), ('Flying', 'Fire'),
       ('Grass', 'Psychic'), (nan, 'Grass'), (nan, 'Grass'),
       (nan, 'Grass'), ('Grass', 'Dragon'), (nan, 'Fire'),
       ('Fighting', 'Fire'), ('Fighting', 'Fire'), ('Fighting', 'Fire'),
       (nan, 'Water'), ('Water', 'Ground'), ('Water', 'Ground'),
       ('Water', 'Ground'), (nan, 'Dark'), (nan, 'Dark'), ('Normal', nan),
       ('Normal', nan), (nan, 'Bug'), (nan, 'Bug'), ('Bug', 'Flying'),
       (nan, 'Bug'), ('Bug', 'Poison'), ('Grass', 'Water'),
       ('Grass', 'Water'), ('Grass', 'Water'), (nan, 'Grass'),
       ('Grass', 'Dark'), ('Grass', 'Dark'), ('Normal', 'Flying'),
       ('Normal', 'Flying'), ('Water', 'Flying'), ('Water', 'Flying'),
       ('Psychic', 'Fairy'), ('Psychic', 'Fairy'), ('Psychic', 'Fairy'),
       ('Psychic', 'Fairy'), ('Bug', 'Water'), ('Bug', 'Flying'),
       (nan, 'Grass'), ('Grass', 'Fighting'), ('Normal', nan),
       ('Normal', nan), ('Normal', nan), ('Bug', 'Ground'),
       ('Bug', 'Flying'), ('Bug', 'Ghost'), ('Normal', nan),
       ('Normal', nan), ('Normal', nan), (nan, 'Fighting'),
       (nan, 'Fighting'), ('Normal', 'Fairy'), ('Rock', nan),
       ('Normal', nan), ('Normal', nan), ('Ghost', 'Dark'),
       ('Ghost', 'Dark'), ('Fairy', 'Steel'), ('Fairy', 'Steel'),
       ('Rock', 'Steel'), ('Rock', 'Steel'), ('Rock', 'Steel'),
       (nan, 'Steel'), ('Psychic', 'Fighting'), ('Psychic', 'Fighting'),
       ('Psychic', 'Fighting'), ('Electric', nan), ('Electric', nan),
       ('Electric', nan), ('Electric', nan), ('Electric', nan),
       (nan, 'Bug'), (nan, 'Bug'), ('Grass', 'Poison'), (nan, 'Poison'),
       (nan, 'Poison'), ('Water', 'Dark'), ('Water', 'Dark'),
       ('Water', 'Dark'), (nan, 'Water'), (nan, 'Water'),
       ('Fire', 'Ground'), ('Fire', 'Ground'), ('Fire', 'Ground'),
       (nan, 'Fire'), (nan, 'Psychic'), (nan, 'Psychic'), ('Normal', nan),
       (nan, 'Ground'), ('Dragon', 'Ground'), ('Dragon', 'Ground'),
       (nan, 'Grass'), ('Grass', 'Dark'), ('Normal', 'Flying'),
       ('Flying', 'Dragon'), ('Fairy', 'Dragon'), ('Normal', nan),
       (nan, 'Poison'), ('Rock', 'Psychic'), ('Rock', 'Psychic'),
       ('Water', 'Ground'), ('Water', 'Ground'), (nan, 'Water'),
       ('Water', 'Dark'), ('Psychic', 'Ground'), ('Psychic', 'Ground'),
       ('Rock', 'Grass'), ('Rock', 'Grass'), ('Rock', 'Bug'),
       ('Rock', 'Bug'), (nan, 'Water'), (nan, 'Water'), ('Normal', nan),
       ('Normal', nan), (nan, 'Ghost'), (nan, 'Ghost'), (nan, 'Ghost'),
       (nan, 'Ghost'), (nan, 'Ghost'), ('Grass', 'Flying'),
       (nan, 'Psychic'), (nan, 'Dark'), (nan, 'Dark'), (nan, 'Psychic'),
       (nan, 'Ice'), (nan, 'Ice'), (nan, 'Ice'), ('Ice', 'Water'),
       ('Ice', 'Water'), ('Ice', 'Water'), (nan, 'Water'), (nan, 'Water'),
       (nan, 'Water'), ('Rock', 'Water'), (nan, 'Water'), (nan, 'Dragon'),
       (nan, 'Dragon'), ('Flying', 'Dragon'), ('Flying', 'Dragon'),
       ('Psychic', 'Steel'), ('Psychic', 'Steel'), ('Psychic', 'Steel'),
       ('Psychic', 'Steel'), ('Rock', nan), (nan, 'Ice'), (nan, 'Steel'),
       ('Psychic', 'Dragon'), ('Psychic', 'Dragon'),
       ('Psychic', 'Dragon'), ('Psychic', 'Dragon'), (nan, 'Water'),
       (nan, 'Water'), (nan, 'Ground'), ('Fire', 'Ground'),
       ('Flying', 'Dragon'), ('Flying', 'Dragon'), ('Psychic', 'Steel'),
       (nan, 'Psychic'), (nan, 'Psychic'), (nan, 'Psychic'),
       (nan, 'Psychic'), (nan, 'Grass'), (nan, 'Grass'),
       ('Grass', 'Ground'), (nan, 'Fire'), ('Fighting', 'Fire'),
       ('Fighting', 'Fire'), (nan, 'Water'), (nan, 'Water'),
       ('Water', 'Steel'), ('Normal', 'Flying'), ('Normal', 'Flying'),
       ('Normal', 'Flying'), ('Normal', nan), ('Normal', 'Water'),
       (nan, 'Bug'), (nan, 'Bug'), ('Electric', nan), ('Electric', nan),
       ('Electric', nan), ('Grass', 'Poison'), ('Grass', 'Poison'),
       ('Rock', nan), ('Rock', nan), ('Rock', 'Steel'), ('Rock', 'Steel'),
       (nan, 'Bug'), ('Grass', 'Bug'), ('Bug', 'Ground'),
       ('Bug', 'Steel'), ('Bug', 'Flying'), ('Bug', 'Flying'),
       ('Bug', 'Flying'), ('Electric', nan), (nan, 'Water'),
       (nan, 'Water'), (nan, 'Grass'), (nan, 'Grass'), (nan, 'Water'),
       ('Water', 'Ground'), ('Normal', nan), ('Ghost', 'Flying'),
       ('Ghost', 'Flying'), ('Normal', nan), ('Normal', nan),
       ('Normal', 'Fighting'), (nan, 'Ghost'), ('Flying', 'Dark'),
       ('Normal', nan), ('Normal', nan), (nan, 'Psychic'),
       ('Poison', 'Dark'), ('Poison', 'Dark'), ('Psychic', 'Steel'),
       ('Psychic', 'Steel'), ('Rock', nan), ('Psychic', 'Fairy'),
       ('Normal', nan), ('Normal', 'Flying'), ('Ghost', 'Dark'),
       ('Dragon', 'Ground'), ('Dragon', 'Ground'), ('Dragon', 'Ground'),
       ('Dragon', 'Ground'), ('Normal', nan), (nan, 'Fighting'),
       ('Fighting', 'Steel'), ('Fighting', 'Steel'), (nan, 'Ground'),
       (nan, 'Ground'), ('Bug', 'Poison'), ('Poison', 'Dark'),
       ('Fighting', 'Poison'), ('Fighting', 'Poison'), (nan, 'Grass'),
       (nan, 'Water'), (nan, 'Water'), ('Water', 'Flying'),
       ('Grass', 'Ice'), ('Grass', 'Ice'), ('Grass', 'Ice'),
       ('Ice', 'Dark'), ('Electric', 'Steel'), ('Normal', nan),
       ('Rock', 'Ground'), (nan, 'Grass'), ('Electric', nan),
       (nan, 'Fire'), ('Flying', 'Fairy'), ('Bug', 'Flying'),
       (nan, 'Grass'), (nan, 'Ice'), ('Flying', 'Ground'),
       ('Ice', 'Ground'), ('Normal', nan), ('Psychic', 'Fighting'),
       ('Psychic', 'Fighting'), ('Rock', 'Steel'), (nan, 'Ghost'),
       ('Ice', 'Ghost'), ('Electric', 'Ghost'), ('Electric', 'Fire'),
       ('Electric', 'Water'), ('Electric', 'Ice'), ('Electric', 'Flying'),
       ('Electric', 'Grass'), (nan, 'Psychic'), (nan, 'Psychic'),
       (nan, 'Psychic'), ('Dragon', 'Steel'), ('Water', 'Dragon'),
       ('Fire', 'Steel'), ('Normal', nan), ('Ghost', 'Dragon'),
       ('Ghost', 'Dragon'), (nan, 'Psychic'), (nan, 'Water'),
       (nan, 'Water'), (nan, 'Dark'), (nan, 'Grass'), ('Grass', 'Flying'),
       ('Normal', nan), ('Psychic', 'Fire'), (nan, 'Grass'),
       (nan, 'Grass'), (nan, 'Grass'), (nan, 'Fire'),
       ('Fighting', 'Fire'), ('Fighting', 'Fire'), (nan, 'Water'),
       (nan, 'Water'), (nan, 'Water'), ('Normal', nan), ('Normal', nan),
       ('Normal', nan), ('Normal', nan), ('Normal', nan), (nan, 'Dark'),
       (nan, 'Dark'), (nan, 'Grass'), (nan, 'Grass'), (nan, 'Fire'),
       (nan, 'Fire'), (nan, 'Water'), (nan, 'Water'), (nan, 'Psychic'),
       (nan, 'Psychic'), ('Normal', 'Flying'), ('Normal', 'Flying'),
       ('Normal', 'Flying'), ('Electric', nan), ('Electric', nan),
       ('Rock', nan), ('Rock', nan), ('Rock', nan), ('Psychic', 'Flying'),
       ('Psychic', 'Flying'), (nan, 'Ground'), ('Steel', 'Ground'),
       ('Normal', nan), ('Normal', 'Fairy'), (nan, 'Fighting'),
       (nan, 'Fighting'), (nan, 'Fighting'), (nan, 'Water'),
       ('Water', 'Ground'), ('Water', 'Ground'), (nan, 'Fighting'),
       (nan, 'Fighting'), ('Grass', 'Bug'), ('Grass', 'Bug'),
       ('Grass', 'Bug'), ('Bug', 'Poison'), ('Bug', 'Poison'),
       ('Bug', 'Poison'), ('Grass', 'Fairy'), ('Grass', 'Fairy'),
       (nan, 'Grass'), (nan, 'Grass'), (nan, 'Water'), ('Dark', 'Ground'),
       ('Dark', 'Ground'), ('Dark', 'Ground'), (nan, 'Fire'),
       (nan, 'Fire'), ('Psychic', 'Fire'), (nan, 'Grass'),
       ('Rock', 'Bug'), ('Rock', 'Bug'), ('Fighting', 'Dark'),
       ('Fighting', 'Dark'), ('Psychic', 'Flying'), (nan, 'Ghost'),
       (nan, 'Ghost'), ('Rock', 'Water'), ('Rock', 'Water'),
       ('Rock', 'Flying'), ('Rock', 'Flying'), (nan, 'Poison'),
       (nan, 'Poison'), (nan, 'Dark'), (nan, 'Dark'), ('Normal', nan),
       ('Normal', nan), (nan, 'Psychic'), (nan, 'Psychic'),
       (nan, 'Psychic'), (nan, 'Psychic'), (nan, 'Psychic'),
       (nan, 'Psychic'), ('Water', 'Flying'), ('Water', 'Flying'),
       (nan, 'Ice'), (nan, 'Ice'), (nan, 'Ice'), ('Normal', 'Grass'),
       ('Normal', 'Grass'), ('Electric', 'Flying'), (nan, 'Bug'),
       ('Bug', 'Steel'), ('Grass', 'Poison'), ('Grass', 'Poison'),
       ('Ghost', 'Water'), ('Ghost', 'Water'), (nan, 'Water'),
       ('Electric', 'Bug'), ('Electric', 'Bug'), ('Grass', 'Steel'),
       ('Grass', 'Steel'), (nan, 'Steel'), (nan, 'Steel'), (nan, 'Steel'),
       ('Electric', nan), ('Electric', nan), ('Electric', nan),
       (nan, 'Psychic'), (nan, 'Psychic'), ('Ghost', 'Fire'),
       ('Ghost', 'Fire'), ('Ghost', 'Fire'), (nan, 'Dragon'),
       (nan, 'Dragon'), (nan, 'Dragon'), (nan, 'Ice'), (nan, 'Ice'),
       (nan, 'Ice'), (nan, 'Bug'), (nan, 'Bug'), ('Electric', 'Ground'),
       (nan, 'Fighting'), (nan, 'Fighting'), (nan, 'Dragon'),
       ('Ghost', 'Ground'), ('Ghost', 'Ground'), ('Dark', 'Steel'),
       ('Dark', 'Steel'), ('Normal', nan), ('Normal', 'Flying'),
       ('Normal', 'Flying'), ('Flying', 'Dark'), ('Flying', 'Dark'),
       (nan, 'Fire'), ('Bug', 'Steel'), ('Dragon', 'Dark'),
       ('Dragon', 'Dark'), ('Dragon', 'Dark'), ('Bug', 'Fire'),
       ('Bug', 'Fire'), ('Fighting', 'Steel'), ('Rock', 'Fighting'),
       ('Grass', 'Fighting'), (nan, 'Flying'), (nan, 'Flying'),
       ('Electric', 'Flying'), ('Electric', 'Flying'), ('Fire', 'Dragon'),
       ('Electric', 'Dragon'), ('Flying', 'Ground'), ('Flying', 'Ground'),
       ('Ice', 'Dragon'), ('Ice', 'Dragon'), ('Ice', 'Dragon'),
       ('Water', 'Fighting'), ('Water', 'Fighting'),
       ('Normal', 'Psychic'), ('Normal', 'Fighting'), ('Bug', 'Steel'),
       (nan, 'Grass'), (nan, 'Grass'), ('Grass', 'Fighting'),
       (nan, 'Fire'), (nan, 'Fire'), ('Psychic', 'Fire'), (nan, 'Water'),
       (nan, 'Water'), ('Water', 'Dark'), ('Normal', nan),
       ('Normal', 'Ground'), ('Normal', 'Flying'), ('Flying', 'Fire'),
       ('Flying', 'Fire'), (nan, 'Bug'), (nan, 'Bug'), ('Bug', 'Flying'),
       ('Normal', 'Fire'), ('Normal', 'Fire'), (nan, 'Fairy'),
       (nan, 'Fairy'), (nan, 'Fairy'), (nan, 'Grass'), (nan, 'Grass'),
       (nan, 'Fighting'), ('Fighting', 'Dark'), ('Normal', nan),
       (nan, 'Psychic'), (nan, 'Psychic'), (nan, 'Psychic'),
       ('Ghost', 'Steel'), ('Ghost', 'Steel'), ('Ghost', 'Steel'),
       ('Ghost', 'Steel'), (nan, 'Fairy'), (nan, 'Fairy'), (nan, 'Fairy'),
       (nan, 'Fairy'), ('Psychic', 'Dark'), ('Psychic', 'Dark'),
       ('Rock', 'Water'), ('Rock', 'Water'), ('Water', 'Poison'),
       ('Poison', 'Dragon'), (nan, 'Water'), (nan, 'Water'),
       ('Electric', 'Normal'), ('Electric', 'Normal'), ('Rock', 'Dragon'),
       ('Rock', 'Dragon'), ('Rock', 'Ice'), ('Rock', 'Ice'),
       (nan, 'Fairy'), ('Flying', 'Fighting'), ('Electric', 'Fairy'),
       ('Rock', 'Fairy'), (nan, 'Dragon'), (nan, 'Dragon'),
       (nan, 'Dragon'), ('Fairy', 'Steel'), ('Grass', 'Ghost'),
       ('Grass', 'Ghost'), ('Grass', 'Ghost'), ('Grass', 'Ghost'),
       ('Grass', 'Ghost'), ('Grass', 'Ghost'), ('Grass', 'Ghost'),
       ('Grass', 'Ghost'), ('Grass', 'Ghost'), ('Grass', 'Ghost'),
       (nan, 'Ice'), (nan, 'Ice'), ('Flying', 'Dragon'),
       ('Flying', 'Dragon'), (nan, 'Fairy'), ('Flying', 'Dark'),
       ('Dragon', 'Ground'), ('Rock', 'Fairy'), ('Rock', 'Fairy'),
       ('Psychic', 'Ghost'), ('Psychic', 'Dark'), ('Water', 'Fire')],
      dtype=object)

#### Cleanup `Name` that contain "Mega".

If you have checked out the pokemon names carefully enough, you should have found there are junk texts in the pokemon names which contain "Mega". We want to clean up the pokemon names. For instance, "VenusaurMega Venusaur" should be "Mega Venusaur", and "CharizardMega Charizard X" should be "Mega Charizard X".

In [298]:
# your code here
for name in pokemon.Name:
    if 'Mega' in name:
        print(name)

VenusaurMega Venusaur
CharizardMega Charizard X
CharizardMega Charizard Y
BlastoiseMega Blastoise
BeedrillMega Beedrill
PidgeotMega Pidgeot
AlakazamMega Alakazam
SlowbroMega Slowbro
GengarMega Gengar
KangaskhanMega Kangaskhan
PinsirMega Pinsir
GyaradosMega Gyarados
AerodactylMega Aerodactyl
MewtwoMega Mewtwo X
MewtwoMega Mewtwo Y
Meganium
AmpharosMega Ampharos
SteelixMega Steelix
ScizorMega Scizor
HeracrossMega Heracross
HoundoomMega Houndoom
TyranitarMega Tyranitar
SceptileMega Sceptile
BlazikenMega Blaziken
SwampertMega Swampert
GardevoirMega Gardevoir
SableyeMega Sableye
MawileMega Mawile
AggronMega Aggron
MedichamMega Medicham
ManectricMega Manectric
SharpedoMega Sharpedo
CameruptMega Camerupt
AltariaMega Altaria
BanetteMega Banette
AbsolMega Absol
GlalieMega Glalie
SalamenceMega Salamence
MetagrossMega Metagross
LatiasMega Latias
LatiosMega Latios
RayquazaMega Rayquaza
LopunnyMega Lopunny
GarchompMega Garchomp
LucarioMega Lucario
AbomasnowMega Abomasnow
GalladeMega Gallade
AudinoMega Audino
DiancieMega Diancie

In [343]:
# import data set from Ironhack's database
pokemon=pd.read_csv('C:/Users/Camille/Documents/Ecole/Ironhack/0323_2020DATAPAR/Labs/module_1/Dataframe-Calculations/Pokemon.csv')

In [300]:
# your code here
for i in pokemon.index:
    if 'Mega' in pokemon.Name[i] and len(pokemon.Name[i])>1:
        pokemon.Name[i]=pokemon.Name[i].split(' ')
        pokemon.Name[i]='Mega '+' '.join(pokemon.Name[i][1:])

print(pokemon.Name)

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3            Mega Venusaur
4               Charmander
              ...
795                Diancie
796           Mega Diancie
797    HoopaHoopa Confined
798     HoopaHoopa Unbound
799              Volcanion
Name: Name, Length: 800, dtype: object

C:\Users\Camille\Anaconda3\Anaconda33\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\Camille\Anaconda3\Anaconda33\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [344]:
pokemon.Name=pokemon.Name.str.split('Mega ').apply(lambda x: 'Mega '+x[1] if len(x)>1 else x[0])

In [ ]:
pokemon.Name = pokemon.Name.str.replace(".*(?=Mega)", "")

In [345]:
# test transformed data
pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,Mega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,Mega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

#### Create a new column called `A/D Ratio` whose value equals to `Attack` devided by `Defense`.

For instance, if a pokemon has the Attack score 49 and Defense score 49, the corresponding `A/D Ratio` is 49/49=1.

In [346]:
# your code here
pokemon['AD_Ratio']=pokemon['Attack']/pokemon['Defense']

#### Identify the pokemon with the highest `A/D Ratio`.

In [338]:
# your code here
pokemon['A/D_Ratio'].nlargest(1)
pokemon.loc[429]

#                            386
Name          DeoxysAttack Forme
Type 1                   Psychic
Type 2                       NaN
Total                        600
HP                            50
Attack                       180
Defense                       20
Sp. Atk                      180
Sp. Def                       20
Speed                        150
Generation                     3
Legendary                   True
A/D_Ratio                      9
Name: 429, dtype: object

#### Identify the pokemon with the lowest A/D Ratio.

In [339]:
# your code here
pokemon['A/D_Ratio'].nsmallest(1)
pokemon.loc[230]

#                   213
Name            Shuckle
Type 1              Bug
Type 2             Rock
Total               505
HP                   20
Attack               10
Defense             230
Sp. Atk              10
Sp. Def             230
Speed                 5
Generation            2
Legendary         False
A/D_Ratio     0.0434783
Name: 230, dtype: object

#### Create a new column called `Combo Type` whose value combines `Type 1` and `Type 2`.

Rules:

* If both `Type 1` and `Type 2` have valid values, the `Combo Type` value should contain both values in the form of `<Type 1> <Type 2>`. For example, if `Type 1` value is `Grass` and `Type 2` value is `Poison`, `Combo Type` will be `Grass-Poison`.

* If `Type 1` has valid value but `Type 2` is not, `Combo Type` will be the same as `Type 1`. For example, if `Type 1` is `Fire` whereas `Type 2` is `NaN`, `Combo Type` will be `Fire`.

In [305]:
pokemon['Type 2'].notnull()[4]

False

In [306]:
# your code here
pokemon['Combo Type']=0

for i in pokemon.index:
    if pokemon['Type 2'].notnull()[i]:
        pokemon['Combo Type'][i]= pokemon['Type 1'][i]+'-'+pokemon['Type 2'][i]
    else:
        pokemon['Combo Type'][i]= pokemon['Type 1'][i]

C:\Users\Camille\Anaconda3\Anaconda33\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Camille\Anaconda3\Anaconda33\lib\site-packages\pandas\core\indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
C:\Users\Camille\Anaconda3\Anaconda33\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [307]:
pokemon.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.000000,Grass-Poison
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.984127,Grass-Poison
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.987952,Grass-Poison
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.813008,Grass-Poison
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1.209302,Fire

#### Identify the pokemon whose `A/D Ratio` are among the top 5.

In [308]:
# your code here
pokemon['A/D Ratio'].nlargest(5)

429    9.000
347    4.500
19     3.750
453    3.125
348    3.000
Name: A/D Ratio, dtype: float64

In [309]:
pokemon.groupby('A/D Ratio')['Name', 'Combo Type'].max()

C:\Users\Camille\Anaconda3\Anaconda33\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.

                         Name     Combo Type
A/D Ratio
0.043478              Shuckle       Bug-Rock
0.181818             Magikarp          Water
0.279070              Bronzor  Steel-Psychic
0.281250                 Onix    Rock-Ground
0.285714   DarmanitanZen Mode   Fire-Psychic
...                       ...            ...
3.000000             Sharpedo     Water-Dark
3.125000             Cranidos           Rock
3.750000        Mega Beedrill     Bug-Poison
4.500000             Carvanha     Water-Dark
9.000000   DeoxysAttack Forme        Psychic

[399 rows x 2 columns]

In [324]:
pokemon.groupby(['Name']).max().sort_values(by = 'A/D Ratio',ascending=False).head(5)

,#,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
Name,,,,,,,,,,,,,,
DeoxysAttack Forme,386,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.000,Psychic
Carvanha,318,Water,Dark,305,45,90,20,65,20,65,3,False,4.500,Water-Dark
Mega Beedrill,15,Bug,Poison,495,65,150,40,15,80,145,1,False,3.750,Bug-Poison
Cranidos,408,Rock,NaN,350,67,125,40,30,30,58,4,False,3.125,Rock
AegislashBlade Forme,681,Steel,Ghost,520,60,150,50,150,50,60,6,False,3.000,Steel-Ghost

In [317]:
pokemon.sort_values(by=['A/D Ratio'], ascending=False).head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.000,Psychic
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,4.500,Water-Dark
19,15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.750,Bug-Poison
453,408,Cranidos,Rock,NaN,350,67,125,40,30,30,58,4,False,3.125,Rock
348,319,Sharpedo,Water,Dark,460,70,120,40,95,40,95,3,False,3.000,Water-Dark

In [347]:
pokemon.loc[pokemon.AD_Ratio.nlargest(5).index]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,AD_Ratio
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.000
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,4.500
19,15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.750
453,408,Cranidos,Rock,NaN,350,67,125,40,30,30,58,4,False,3.125
348,319,Sharpedo,Water,Dark,460,70,120,40,95,40,95,3,False,3.000

#### For the 5 pokemon printed above, aggregate `Combo Type` and use a list to store the unique values.

Your end product is a list containing the distinct `Combo Type` values of the 5 pokemon with the highest `A/D Ratio`.

In [310]:
# your code here
lst_combo=[]
pokemon_name=['Sharpedo', 'Cranidos', 'Mega Beedrill', 'Carvanha', 'DeoxysAttack Forme']

for i in pokemon.index:
    if pokemon['Name'][i] in pokemon_name:
        lst_combo.append(pokemon['Combo Type'][i])
    else:
        lst_combo
    
lst_combo

['Bug-Poison', 'Water-Dark', 'Water-Dark', 'Psychic', 'Rock']

#### For each of the `Combo Type` values obtained from the previous question, calculate the mean scores of all numeric fields across all pokemon.

Your output should look like below:

![Aggregate](../images/aggregated-mean.png)

In [312]:
# your code here
table=pokemon.pivot_table(index='Combo Type').reset_index()
table.loc[table['Combo Type'].isin(lst_combo)]

,Combo Type,#,A/D Ratio,Attack,Defense,Generation,HP,Legendary,Sp. Atk,Sp. Def,Speed,Total
8,Bug-Poison,199.166667,1.315989,68.333333,58.083333,2.333333,53.750000,0.000000,42.500000,59.333333,65.916667,347.916667
109,Psychic,381.973684,1.164196,64.947368,67.236842,3.342105,72.552632,0.236842,98.552632,82.394737,78.868421,464.552632
117,Rock,410.111111,1.260091,103.333333,107.222222,3.888889,67.111111,0.111111,40.555556,58.333333,32.888889,409.444444
140,Water-Dark,347.666667,2.291949,120.000000,65.166667,3.166667,69.166667,0.000000,88.833333,63.500000,87.166667,493.833333

In [320]:
pokemon.pivot_table(index='Combo Type').reset_index().loc[table['Combo Type'].isin(lst_combo)]

,Combo Type,#,A/D Ratio,Attack,Defense,Generation,HP,Legendary,Sp. Atk,Sp. Def,Speed,Total
8,Bug-Poison,199.166667,1.315989,68.333333,58.083333,2.333333,53.750000,0.000000,42.500000,59.333333,65.916667,347.916667
109,Psychic,381.973684,1.164196,64.947368,67.236842,3.342105,72.552632,0.236842,98.552632,82.394737,78.868421,464.552632
117,Rock,410.111111,1.260091,103.333333,107.222222,3.888889,67.111111,0.111111,40.555556,58.333333,32.888889,409.444444
140,Water-Dark,347.666667,2.291949,120.000000,65.166667,3.166667,69.166667,0.000000,88.833333,63.500000,87.166667,493.833333